temperature: 0
max_tokens: 0
max_context_window: 500000
base_url: https://openrouter.ai/api/v1
api_key: 
timeout: 600
stream_timeout: 30
first_chunk_timeout: 30
models:
- openai/google/gemini-3-flash-preview
figure_models:
- google/gemini-3-pro-image-preview
compressor_models:
- openai/google/gemini-3-flash-preview
read_figure_models:
- openai/google/gemini-3-flash-preview
multimodal: true
compressor_multimodal: true
